services:
  - type: web
    name: tenderbidding-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn asian_paints_rfp_autobot:app --host 0.0.0.0 --port 10000
